"""add resume tables

Revision ID: 001
Revises:
Create Date: 2026-02-07 12:00:00.000000

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 创建简历主表
    op.create_table(
        'resumes',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('resume_type', sa.String(length=20), nullable=False),
        sa.Column('title', sa.String(length=100), nullable=True),
        sa.Column('status', sa.String(length=20), nullable=True),
        sa.Column('full_name', sa.String(length=50), nullable=False),
        sa.Column('phone', sa.String(length=20), nullable=False),
        sa.Column('email', sa.String(length=100), nullable=False),
        sa.Column('current_city', sa.String(length=50), nullable=True),
        sa.Column('target_cities', sa.String(length=200), nullable=True),
        sa.Column('job_status', sa.String(length=20), nullable=True),
        sa.Column('target_positions', sa.String(length=200), nullable=True),
        sa.Column('work_years', sa.Integer(), nullable=True),
        sa.Column('current_company', sa.String(length=100), nullable=True),
        sa.Column('current_position', sa.String(length=100), nullable=True),
        sa.Column('expected_salary', sa.String(length=50), nullable=True),
        sa.Column('self_evaluation', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resumes_user_id'), 'resumes', ['user_id'], unique=False)
    
    # 创建教育经历表
    op.create_table(
        'educations',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('resume_id', sa.Integer(), nullable=False),
        sa.Column('school_name', sa.String(length=100), nullable=False),
        sa.Column('degree', sa.String(length=20), nullable=False),
        sa.Column('major', sa.String(length=100), nullable=False),
        sa.Column('start_date', sa.Date(), nullable=False),
        sa.Column('end_date', sa.Date(), nullable=True),
        sa.Column('gpa', sa.String(length=20), nullable=True),
        sa.Column('courses', sa.Text(), nullable=True),
        sa.Column('honors', sa.Text(), nullable=True),
        sa.Column('sort_order', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_educations_resume_id'), 'educations', ['resume_id'], unique=False)
    
    # 创建工作/实习经历表
    op.create_table(
        'work_experiences',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('resume_id', sa.Integer(), nullable=False),
        sa.Column('exp_type', sa.String(length=20), nullable=False),
        sa.Column('company_name', sa.String(length=100), nullable=False),
        sa.Column('position', sa.String(length=100), nullable=False),
        sa.Column('start_date', sa.Date(), nullable=False),
        sa.Column('end_date', sa.Date(), nullable=True),
        sa.Column('description', sa.Text(), nullable=False),
        sa.Column('sort_order', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_work_experiences_resume_id'), 'work_experiences', ['resume_id'], unique=False)
    
    # 创建项目经历表
    op.create_table(
        'projects',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('resume_id', sa.Integer(), nullable=False),
        sa.Column('project_name', sa.String(length=100), nullable=False),
        sa.Column('role', sa.String(length=100), nullable=False),
        sa.Column('start_date', sa.Date(), nullable=False),
        sa.Column('end_date', sa.Date(), nullable=True),
        sa.Column('project_link', sa.String(length=500), nullable=True),
        sa.Column('description', sa.Text(), nullable=False),
        sa.Column('sort_order', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_resume_id'), 'projects', ['resume_id'], unique=False)
    
    # 创建技能表
    op.create_table(
        'skills',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('resume_id', sa.Integer(), nullable=False),
        sa.Column('skill_name', sa.String(length=50), nullable=False),
        sa.Column('proficiency', sa.String(length=20), nullable=False),
        sa.Column('sort_order', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skills_resume_id'), 'skills', ['resume_id'], unique=False)
    
    # 创建语言能力表
    op.create_table(
        'languages',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('resume_id', sa.Integer(), nullable=False),
        sa.Column('language', sa.String(length=20), nullable=False),
        sa.Column('proficiency', sa.String(length=50), nullable=False),
        sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_languages_resume_id'), 'languages', ['resume_id'], unique=False)
    
    # 创建获奖经历表
    op.create_table(
        'awards',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('resume_id', sa.Integer(), nullable=False),
        sa.Column('award_name', sa.String(length=200), nullable=False),
        sa.Column('award_date', sa.Date(), nullable=True),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('sort_order', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_awards_resume_id'), 'awards', ['resume_id'], unique=False)
    
    # 创建作品表
    op.create_table(
        'portfolios',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('resume_id', sa.Integer(), nullable=False),
        sa.Column('work_name', sa.String(length=100), nullable=False),
        sa.Column('work_link', sa.String(length=500), nullable=True),
        sa.Column('attachment_url', sa.String(length=500), nullable=True),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('sort_order', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_portfolios_resume_id'), 'portfolios', ['resume_id'], unique=False)
    
    # 创建社交账号表
    op.create_table(
        'social_links',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('resume_id', sa.Integer(), nullable=False),
        sa.Column('platform', sa.String(length=50), nullable=False),
        sa.Column('url', sa.String(length=500), nullable=False),
        sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_social_links_resume_id'), 'social_links', ['resume_id'], unique=False)
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_social_links_resume_id'), table_name='social_links')
    op.drop_table('social_links')
    op.drop_index(op.f('ix_portfolios_resume_id'), table_name='portfolios')
    op.drop_table('portfolios')
    op.drop_index(op.f('ix_awards_resume_id'), table_name='awards')
    op.drop_table('awards')
    op.drop_index(op.f('ix_languages_resume_id'), table_name='languages')
    op.drop_table('languages')
    op.drop_index(op.f('ix_skills_resume_id'), table_name='skills')
    op.drop_table('skills')
    op.drop_index(op.f('ix_projects_resume_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_work_experiences_resume_id'), table_name='work_experiences')
    op.drop_table('work_experiences')
    op.drop_index(op.f('ix_educations_resume_id'), table_name='educations')
    op.drop_table('educations')
    op.drop_index(op.f('ix_resumes_user_id'), table_name='resumes')
    op.drop_table('resumes')
    # ### end Alembic commands ###
